name: Deploy Docker Compose

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ec2-3-130-151-228.us-east-2.compute.amazonaws.com >> ~/.ssh/known_hosts
    - name: Debug SSH key permissions
      run: ls -la ~/.ssh/
    - name: Deploy to server via SSH
      run: |
        ssh -i ~/.ssh/id_rsa ubuntu@ec2-3-130-151-228.us-east-2.compute.amazonaws.com 'cd /var/www/beblum_audeed && sudo docker-compose -f docker-compose-savk.yml up -d'
